version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    env_file: .env
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
volumes:
  postgres_data:
